information_checklist_model = "gpt-4o"
information_checklist_instructions = "You are an automated checklist. I need you to carefully read a paragraph to check if it contains some information. Your response should be a valid jsonlist called 'information_checklist' where each json object has 'information' and 'check' attributes. The 'check' can only be 'Yes', 'No', or 'Wrong'. If the paragraph contains the information, then the 'check' should be 'Yes' and if it doesn't contain the information or the informaion is unknown, the check should be 'No'. If the paragraph contradicts the information, then the 'check' should be 'Wrong'. The list of 'information' is given as follows:\n"
information_checklist_prompt_pre = "Read the given paragraph to check if it contains the information. Your 'check' should be based ONLY on the paragraph given below and can only be 'Yes', 'No', or 'Wrong'. Do NOT return 'Unknown'. \nParagraph: "

formula_reader_model = "gpt-4o"
formula_reader_instructions = "You are a latex formula reader. I need you to read over an array in latex and give me a formula that answers the given question. Your response should be a json object called 'formula'. While writing the formula, force should be denoted by 'F', distance/displacement should be denoted by 's', angle should be denoted by 'theta', mass should be denoted by 'm', acceleration should be denoted by 'a', velocity should be denoted by 'v', height should be denoted by 'h', acceleration due to gravity should be denoted by 'g', gravitational potential energy should be denoted by 'E_p', kinetic energy should be denoted by 'E_k', and spring potential energy should be denoted by 'E_s'. You can NOT use any other symbols in the formula. Follow python syntax while writing the formula. If the formula isn't mentioned, respond with 'Unknown' in the 'formula' attribute. The given question is:\n"
formula_reader_prompt_pre = "Read this array and give me a formual that answers the question. Your answer should be based ONLY on the array given below, even if it contradicts common knowledge. \nArray: "

print_working_json_model = "gpt-4o"
print_working_json_instructions = "You are a paraphraser. I need you to read a question and it's working and paraphrase it. Your response should be a json object which has the 'working' attribute. The 'working' will be a paraphrased version of the given working."
print_working_json_prompt_pre = "Help me paraphrase the working to the given question. If no working is given, return an empty string for working. \nQuestion: "
print_working_json_prompt_post = "\nWorking: "